### ISSUE TITLE
[Frontend] - Relocate the Paper Analysis and File Upload into the Manual Upload Page (Dataset Upload)

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#290] opened 2021-01-26 18:51 UTC
As a user, I want all the ways to upload a dataset in the same page.

**Description :**
As of now, the file upload and the pdf paper upload are in there own pages. This should move those options to the dataset Upload page.

**Mockup :**
To come

Acceptance Criteria
This should retain all the functionality of the file upload
This should allow drag and drop for both the PDF and JSON

**Comment by ds161833** [comment] 2021-03-15 22:28
closing as a duplicate of a finished story

**Closed as completed by ds161833** 2021-03-15 22:28 UTC
Labels: enhancement, Frontend
